name: Github Actions
on:
  pull_request:
    branches:
      - 'main'
      - 'test'

jobs:
  Springboot-Setup:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo "hello world"
