name: Github Actions
on:
  pull_request:
    branches:
      - 'main'

jobs:
  Springboot-Setup:
    if: github.event.pull_request.head.repo.fork
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo "hello world"
